apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Let's Encrypt staging server
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email for certificate expiration notifications
    email: admin@example.com  # CHANGE THIS TO YOUR EMAIL!
    # Secret to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging-key
    # HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: traefik
