apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: ejbca
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: ejbca_root_pass_123
  MYSQL_PASSWORD: ejbca_pass_123
  MYSQL_USER: ejbca
  MYSQL_DATABASE: ejbca
